import { useState } from 'react'
import { jsPDF } from 'jspdf'
import { generateUsageHistory } from '../data/simulateData.js'

const PERIODS = {
  daily: { label: 'Daily', days: 1, title: 'Daily Water Report' },
  weekly: { label: 'Weekly', days: 7, title: 'Weekly Water Report' },
  monthly: { label: 'Monthly', days: 30, title: 'Monthly Water Report' },
}

export default function MunicipalReport({ stats }) {
  const [period, setPeriod] = useState('weekly')

  function handleGenerate() {
    const { days, title } = PERIODS[period]
    // Aggregate real generated history over the selected period.
    const periodHistory = generateUsageHistory(days)
    const totalLiters = periodHistory.reduce((a, d) => a + d.liters, 0)
    const avgLiters = Math.round(totalLiters / periodHistory.length)
    const peakDay = periodHistory.reduce((max, d) => (d.liters > max.liters ? d : max), periodHistory[0])
    const baseline = 220
    const totalSaved = Math.max(0, periodHistory.reduce((a, d) => a + Math.max(0, baseline - d.liters), 0))

    const doc = new jsPDF()
    const marginX = 18
    let y = 22

    doc.setFillColor(11, 30, 39)
    doc.rect(0, 0, 210, 32, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(18)
    doc.text(`AquaMind AI — Municipal ${title}`, marginX, y)
    y += 8
    doc.setFontSize(10)
    doc.setTextColor(200, 230, 235)
    doc.text(`Generated: ${new Date().toLocaleString()} · Period: ${PERIODS[period].label} (${days} day${days > 1 ? 's' : ''})`, marginX, y)

    y = 46
    doc.setTextColor(20)
    doc.setFontSize(13)
    doc.text('Period Summary', marginX, y)

    const rows = [
      [`Total usage over period`, `${totalLiters.toLocaleString()} L`],
      [`Average daily usage`, `${avgLiters} L`],
      [`Peak usage day`, `${peakDay.day} (${peakDay.liters} L)`],
      [`Estimated liters saved vs. baseline`, `${totalSaved.toLocaleString()} L`],
      [`Current usage`, `${stats.todayUsage} L`],
      [`7-day AI forecast average`, `${stats.forecastAvg} L`],
      [`Leak/anomaly confidence`, `${stats.anomalyConfidence}%`],
      [`Water credit score`, `${stats.creditScore ?? 'N/A'} / 100`],
    ]

    y += 8
    doc.setFontSize(11)
    rows.forEach(([label, value]) => {
      doc.setTextColor(90)
      doc.text(label, marginX, y)
      doc.setTextColor(20)
      doc.text(String(value), 140, y)
      y += 8
    })

    y += 6
    doc.setDrawColor(200)
    doc.line(marginX, y, 192, y)
    y += 10
    doc.setFontSize(13)
    doc.setTextColor(20)
    doc.text('Recommended Municipal Actions', marginX, y)
    y += 8
    doc.setFontSize(10)
    doc.setTextColor(70)
    const actions = [
      '- Prioritize leak-repair crews in zones with rising anomaly confidence scores.',
      '- Issue public advisories during low-rainfall periods flagged by the drought risk score.',
      '- Recognize top-performing households/wards with tariff incentives.',
      '- Monitor reservoir surface trends via the Satellite Monitor page.',
    ]
    actions.forEach((a) => {
      doc.text(a, marginX, y)
      y += 7
    })

    y += 10
    doc.setFontSize(9)
    doc.setTextColor(140)
    doc.text('Generated by AquaMind AI — AI for Water Conservation and Management', marginX, y)
    doc.text('Note: figures are based on simulated demo data for this hackathon build.', marginX, y + 5)

    doc.save(`AquaMind-${PERIODS[period].label}-Report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', gap: 6 }}>
        {Object.entries(PERIODS).map(([key, p]) => (
          <button
            key={key}
            className={`btn ${period === key ? '' : 'ghost'}`}
            style={{ flex: 1, fontSize: 12, padding: '7px 10px' }}
            onClick={() => setPeriod(key)}
          >
            {p.label}
          </button>
        ))}
      </div>
      <button className="btn" onClick={handleGenerate}>
        🏛️ Generate {PERIODS[period].label} Report (PDF)
      </button>
    </div>
  )
}
